config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories
  resources :products
  resources :sub_categories
  resources :reviews
  resources :cart_line_items

  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_line_item.rb
class CartLineItem < ApplicationRecord
  validates_presence_of :product_id, :user_id, :quantity
  validates_numericality_of :product_id, :user_id, greater_than: 0
  validates_numericality_of :quantity, within: 1..5

  belongs_to :user
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord

  #association
  has_many :products
  has_many :sub_categories

  #validation
  validates_presence_of :name
  validates_uniqueness_of :name

  def formatted_name
    "#{self.id} - #{self.name}"
  end
end

app/models/product.rb
class Product < ApplicationRecord

  #association
  belongs_to :category
  belongs_to :sub_category
  has_many :reviews
  has_many :cart_line_items

  #inbuilt validation
  validates_presence_of :name, :price, :category_id, :description, :stock, :sub_category_id
  validates_numericality_of :price, greater_than: 1
  validates_numericality_of :stock, greater_than_or_equal: 0
  validates_numericality_of :category_id, :sub_category_id, greater_than: 0
  validates_length_of :description, minimum: 10
  validates_length_of :name, minimum: 4
  validate :check_for_cod_eligibility_on_price
  validate :check_for_cod_eligibility_based_on_category
  validate :check_for_cod_eligibility

  #custom validation

  def check_for_cod_eligibility_on_price
    if !self.price.nil?
      if self.price > 50000 && self.cod_eligibility
        self.errors.add(:cod_eligibility, "not available for products greater than 50000")
      end
    end
  end

  def check_for_cod_eligibility_based_on_category
    if !self.category_id.nil?
      if self.category_id == 1 && self.cod_eligibility
        self.errors.add(:cod_eligibility, "not available for products belongs to Electronics")
      end
    end
  end

  def check_for_cod_eligibility
    if !self.category_id.nil?
      if self.cod_eligibility && (self.category_id == 1 || self.category_id == 3)
        self.errors.add(:cod_eligibility, "not available for products belongs to Electronics or Equipment")
      end
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates_presence_of :product_id, :user_id, :title, :rating
  validates_numericality_of :product_id, :user_id, greater_than: 0
  validates_numericality_of :rating, within: 1..5 #inclusive rang if ... exclusive rang
  validates_length_of :body, minimum: 10, allow_blank: true
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  validates_presence_of :name, :category_id
  validates_uniqueness_of :name
  validates_numericality_of :category_id, greater_than: 0

  belongs_to :category
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :cart_line_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cart_line_items_controller.rb
class CartLineItemsController < ApplicationController

  def index
    @cart_line_items = current_user.cart_line_items
  end

  def create
    @cart_line_item = CartLineItem.new(cart_line_item_params)
    @cart_line_item.user_id = current_user.id
    if @cart_line_item.save
      redirect_to cart_line_items_path, notice: "Product added to your cart"
    end
  end

  private

  def cart_line_item_params
    params[:cart_line_item].permit(:product_id, :quantity)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: "Successfully created #{@category.name}"
    else
      render action: "new"
    end
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products #Product.where('category_id = ?', @category.id)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    previous_name = @category.name
    if @category.update_attributes(category_params)
      redirect_to category_path(@category.id), notice: "Successfully updated #{previous_name} to #{@category.name}"
    else
      render action: "edit"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, notice: "Successfully deleted #{@category.name}"
  end

  private

  def category_params
    params[:category].permit(:name)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to product_path(@product.id), notice: "Successfully added #{@product.name}"
    else
      render action: "new"
    end
  end

  def show
    @review = Review.new
    @cart_line_item = CartLineItem.new
    begin
      @product = Product.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to products_path, notice: "Record Not Found"
    end

  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    previous_product = @product.name
    if @product.update_attributes(product_params)
      redirect_to product_path(@product.id), notice: "Successfully updated #{previous_product} to #{@product.name}"
    else
      render action: "edit"
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path, notice: "Successfully deleted #{@product.name}"
  end

  private

  # strong parameter / safe guard from mass assignment
  def product_params
    params[:product].permit(:name, :description, :price, :category_id, :stock, :cod_eligibility, :image_url, :sub_category_id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    #@reviews = Review.where('user_id = ?', current_user.id)
    @reviews = current_user.reviews
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to :back, notice: "Thank you for the review"
    end
  end

  private
  def review_params
    params[:review].permit(:title,:body,:rating,:product_id)
  end
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  def index
    @sub_categories = SubCategory.all
  end

  def new
    @sub_category = SubCategory.new
  end

  def create
    @sub_category = SubCategory.new(sub_ctegory_param)
    if @sub_category.save
      redirect_to sub_category_path(@sub_category.id), notice: "Successfully created"
    else
      render action: "new"
    end
  end

  def show
    @sub_category = SubCategory.find(params[:id])
  end

  def edit
    @sub_category = SubCategory.find(params[:id])
  end

  def update
    @sub_category = SubCategory.find(params[:id])
    if @sub_category.update_attributes(sub_ctegory_param)
      redirect_to sub_category_path(@sub_category.id), notice: "Successfully updated"
    else
      render action: "edit"
    end
  end

  def destroy
    @sub_category = SubCategory.find(params[:id])
    @sub_category.destroy
    redirect_to sub_categories_path
  end

  private
  def sub_ctegory_param
    params[:sub_category].permit(:name, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_line_items_helper.rb
module CartLineItemsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/cart_line_items/index.html.erb
<% if @cart_line_items.empty? %>
  <p>your cart is empty. Continue shopping <%= link_to "here", products_path %></p>
<% else %>
  <table border="1">
    <thead>
      <tr>
        <th>#</th>
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      <% @cart_line_items.each_with_index do |cart_line_item, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= cart_line_item.product.name %></td>
          <td><%= cart_line_item.product.price %></td>
          <td><%= cart_line_item.quantity %></td>
          <td><%= cart_line_item.product.price * cart_line_item.quantity %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<%= form_for @category do |f| %>
<!-- <label>Name : </label> -->
<% if @category.errors.any? %>
  <h3>Errors : </h3>
  <ul>
  <% @category.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>
  <%= f.label :name %>
  <%= f.text_field :name %><br/>
  <%= f.submit "Submit" %><br/>
  <%= link_to "back", category_path(@category.id) %> <br/>
  <%= link_to "List", categories_path %>
<% end %>

app/views/categories/index.html.erb
<h2>Listing Categories : <%= @categories.length %></h2>
<%if @categories.empty? %>
  <p>Category is not been added yet</p>
<% else %>
  <ol>
    <% @categories.each do |category| %>
      <li>
        <%= link_to category.name, category_path(category.id)%>
        (<%= Product.where('category_id = ?', category.id).length %>)
        
      </li>
    <% end %>
  </ol>
<% end %>


<% if user_signed_in? && current_user.is_admin %>
  <%= link_to "Add Category (ror best)", new_category_path %>
<% end %>
<!-- new_category_path return string "/categories/new" -->
<%#= link_to "Add Category (ror)", "/categories/new" %>
<!-- <a href="/categories/new" target="_blank">Add Category </a>` -->

app/views/categories/new.html.erb
<h2>Add Category</h2>

<%= form_for @category do |f| %>
<!-- <label>Name : </label> -->
<% if @category.errors.any? %>
  <h3>Errors : </h3>
  <ul>
  <% @category.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>
<%= f.label :name %>
<%= f.text_field :name %><br/>
<%= f.submit "Submit" %>
<% end %>

<!-- <form action=".." method="post">
<label>Name</label>
<input type="text">
<input type="submit">
</form> -->

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>

<% if user_signed_in? && current_user.is_admin %>
  <%= link_to "Edit", edit_category_path(@category.id) %> |
  <%= link_to "destroy", category_path(@category.id), method: :delete, data: {confirm: "Are you sure?"} %>
  <% end %>
 | <%= link_to "Back", categories_path %>

<% @category.sub_categories.each do |sub_category| %>
  <h3><%= link_to sub_category.name.upcase, sub_category_path(sub_category.id) %>(<%= sub_category.products.size %>)</h3>
  <ul>
    <% sub_category.products.each do |product| %>
      <li><%= link_to product.name, product_path(product.id)  %></li>
    <% end %>
  </ul>
<% end %>

 <!--  <% products_lessthan_500 = Product.where('price < ? AND category_id = ?', 500, @category.id) %>
  <% products_greater_500 = Product.where('price > ? AND category_id = ?', 500, @category.id) %>

  <% if @products.empty? %>
    <p> No Products Found </p>
  <% else %>
    <ol>
      <% @products.each do |product| %>
        <li>
            <%= link_to product.name, product_path(product.id) %> INR <%= product.price %> Stock - <%= product.stock %>
          </li>
        <% end %>
    </ol>
  <% end %>


  <p>Product less than 500 ===== <%= products_lessthan_500.length %></p>
  <% if products_lessthan_500.empty? %>
    <p> No Product Found </p>
  <% else %>
    <ol>
      <% products_lessthan_500.each do |product| %>
        <li>
            <%= product.name %> INR <%= product.price %> Stock - <%= product.stock %>
          </li>
        <% end %>
    </ol>
  <% end %>


  <p>Product greater than 500 ===== <%= products_greater_500.length %></p>
  <% if products_greater_500.empty? %>
    <p> No Product Found </p>
  <% else %>
    <ol>
      <% products_greater_500.each do |product| %>
        <li>
            <%= product.name %> INR <%= product.price %> Stock - <%= product.stock %>
          </li>
        <% end %>
    </ol>
  <% end %> -->
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      Welcome <%= current_user.email %><br/>
      <%= link_to "Account Setting", edit_user_registration_path %>
      <%= link_to "Log Out", destroy_user_session_path, method: :delete %><br/>
      <%= link_to "My Reviews", reviews_path %><br/>
      <%= link_to "My Cart", cart_line_items_path %>(<%= current_user.cart_line_items.size %>)<br/>
    <% else %>
      <%= link_to "Login", new_user_session_path %> | <%= link_to "Registration", new_user_registration_path %><br/>
    <% end %>
    <%= link_to "Categories", categories_path %> | <%= link_to "Products", products_path %> | <%= link_to "Sub Category", sub_categories_path %>
    <br/>
    <%= notice %>
    <%= alert %>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h2>Edit Product</h2>

<% if @product.errors.any? %>
  <h3>Errors : </h3>
  <ul>
  <% @product.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for @product do |f| %>
  <%= f.label :name %><br/>
  <%= f.text_field :name %><br/>

  <%= f.label :description %><br/>
  <%= f.text_area :description, rows: 10, cols: 50 %><br/>

  <%= f.label :price %><br/>
  <%= f.text_field :price %><br/>

  <%= f.label :category_id %><br/>
  <%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Category" %><br/>

  <%= f.label :sub_category_id %><br/>
  <%= f.collection_select :sub_category_id, SubCategory.all, :id, :name, prompt: "Select Sub Category" %><br/>

  <%= f.label :stock %><br/>
  <%= f.text_field :stock %><br/>

  <%= f.label :cod_eligibility %><br/>
  <%= f.check_box :cod_eligibility %><br/>

  <%= f.label :image_url %><br/>
  <%= f.text_field :image_url %><br/>

  <%= f.submit %>
<% end %>

app/views/products/index.html.erb
<h2>Listing Products : <%= @products.length %></h2>
<% if user_signed_in? && current_user.is_admin %>
  <%= link_to "Add Product", new_product_path%>
<% end %>

<% if @products.empty? %>
  <p>Products is not been added yet</p>
<% else %>
  <ol>
    <% @products.each do |product| %>
      
      <li>
      <%= link_to product.name, product_path(product.id) %> Category Name === <%= product.category.try(:name) %>
      <%#= @name = Category.find(product.category_id).name %>
      </li>
    <% end %>
  </ol>
<% end %>
<label>Price</label>
<%#= link_to "Low To High" %>
<%#= link_to "High To Low" %>

app/views/products/new.html.erb
<h2>New Product</h2>

<% if @product.errors.any? %>
  <h3>Errors : </h3>
  <ul>
  <% @product.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for @product do |f| %>
  <%= f.label :name %><br/>
  <%= f.text_field :name %><br/>

  <%= f.label :description %><br/>
  <%= f.text_area :description, rows: 10, cols: 50 %><br/>

  <%= f.label :price %><br/>
  <%= f.text_field :price %><br/>

  <%= f.label :category_id %><br/>
  <%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Category" %><br/>

  <%= f.label :sub_category_id %><br/>
  <%= f.collection_select :sub_category_id, SubCategory.all, :id, :name, prompt: "Select Sub Category" %><br/>

  <%= f.label :stock %><br/>
  <%= f.text_field :stock %><br/>

  <%= f.label :cod_eligibility %><br/>
  <%= f.check_box :cod_eligibility %><br/>

  <%= f.label :image_url %><br/>
  <%= f.text_field :image_url %><br/>

  <%= f.submit %>
<% end %>

app/views/products/show.html.erb
<h2>Product Description</h2>
Name::          <%= @product.name %><br/>
Description:    <%= @product.description %><br/>
INR:            <%= @product.price %><br/>
Stock:          <%= @product.stock %><br/>
Category:       <%= link_to @product.category.name, category_path(@product.category_id) %><br>
Sub Category    <%= link_to @product.sub_category.name, sub_category_path(@product.sub_category_id) %><br/>
Cod Eligibility:<%= @product.cod_eligibility %><br/>
Image URL:      <%= @product.image_url %><br/><br/>


<%= form_for @cart_line_item do |f| %>
  <%= f.label :quantity %><br/>
  <%= f.select :quantity, [1,2,3,4,5] %><br/>
  <%= f.hidden_field :product_id, value: @product.id %><br/>
  <%= f.submit "Add To Cart" %>
<% end %>

<% if user_signed_in? && current_user.is_admin %>
  <%= link_to "Edit", edit_product_path(@product.id) %><br/>
  <%= link_to "Delete", product_path(@product.id), method: :delete, data: {confirm: "Are you sure?"} %><br/>
<% end %>

<h2>Reviews : (<%= @product.reviews.length %>)</h2>
<ol>
  <% @product.reviews.each do |review| %>
    <li>
      <%= review.user.email %> rated <%= "*" * review.rating %><br/>
      <%= review.title %> - <%= review.body %> on <%= review.created_at %><br/>

      <% if review.user_id == current_user.id %>
        <%= link_to "Delete" %>
      <% end %>
    </li>
  <% end %>
</ol>

<h2>Add Review</h2>

<%= form_for @review do |f| %>
  <%= f.label :rating %><br/>
  <%= f.radio_button :rating, 1 %> Select 1
  <%= f.radio_button :rating, 2 %> Select 2
  <%= f.radio_button :rating, 3 %> Select 3
  <%= f.radio_button :rating, 4 %> Select 4
  <%= f.radio_button :rating, 5 %> Select 5<br/>

  <%= f.label :title %><br/>
  <%= f.text_field :title %><br/>

  <%= f.label :body %><br/>
  <%= f.text_area :body %><br/>


  <%= f.hidden_field :product_id, value: @product.id %><br/>

  <%= f.submit %>
<% end %>

<%= link_to "Back", products_path  %><br/>

app/views/reviews/index.html.erb
<h2>Reviews</h2>

<ol>
  <% @reviews.each do |review| %>
  <h3><%= link_to review.product.name, product_path(review.product.id) %></h3>
   <li> <%= review.title %><br/>
    <%= review.body %><br/></li>
  <% end %>
</ol>
<%= link_to "Back", products_path %>

app/views/sub_categories/edit.html.erb
<h2>Edit Sub Category</h2>

<%= form_for @sub_category do |f| %>
  <% if @sub_category.errors.any? %>
  <h3>
    Errors:
    <ul>
      <% @sub_category.errors.full_messages do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </h3>
  <% else %>
    <%= f.label :name %><br/>
    <%= f.text_field :name %><br/>
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Category" %><br/>
    <%= f.submit %>
  <% end %> 
<% end %>

app/views/sub_categories/index.html.erb
<h2>Index Page</h2>

<% if user_signed_in? && current_user.is_admin %>
  <%= link_to "Add Sub Category", new_sub_category_path %>
<% end %>

<% if @sub_categories.empty? %>
  <p>No sub category</p>
<% else %>
  <ol>
  <% @sub_categories.each do |sub_category| %>
    <li>
      <%= link_to sub_category.name, sub_category_path(sub_category.id) %>
    </li>
  <% end %>
  </ol>
<% end %>

app/views/sub_categories/new.html.erb
<h2>Add Sub Category</h2>

<%= form_for @sub_category do |f| %>
  <% if @sub_category.errors.any? %>
  <h3>
    Errors:
    <ul>
      <% @sub_category.errors.full_messages do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </h3>
  <% else %>
    <%= f.label :name %><br/>
    <%= f.text_field :name %><br/>
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Category" %><br/>
    <%= f.submit %>
  <% end %> 
<% end %>

app/views/sub_categories/show.html.erb
<h2>Show Page</h2>

<!-- Sub Category : <%= @sub_category.name %><br/>
Category : <%= @sub_category.category.name %><br/> -->

<% if user_signed_in? && current_user.is_admin %>
  <%= link_to "Edit", edit_sub_category_path(@sub_category.id) %><br/>
  <%= link_to "Destroy", sub_category_path(@sub_category.id), method: :delete, data: {confirm: "Are you sure?"} %><br/>
<% end %>
<%= link_to "Back", sub_categories_path %>
<ul>
<% @sub_category.products.each do |product| %>
  <li><%= link_to product.name, product_path(product.id) %></li>
<% end %>
</ul>